In [ ]:
import pandas as pd
df_molecule= pd.read_csv('dataset_training_fingerprint.tsv', sep = '\t')
df_column= pd.read_csv('dataset_training_Columna.tsv', sep = '\t')
df_gradient= pd.read_csv('dataset_training_gradient.tsv', sep = '\t')

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [ ]:
df_molecule.head()

   id molecule_id      rt                                        fingerprint
0   1  0001_00001  12.070  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1   1  0001_00002  15.990  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
2   1  0001_00003   8.675  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
3   1  0001_00004   7.750  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
4   1  0001_00005  10.600  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

In [ ]:
df_molecule.shape

(213098, 4)

In [ ]:
df_molecule=df_molecule[df_molecule["id"]!=20].copy()

In [ ]:
df_molecule.shape

(212919, 4)

In [ ]:
df_column = df_column.drop(columns=["molecule_id"])
df_column = df_column.drop(columns=["rt"])
df_column.head()

,id,column.name,column.usp.code,column.length,column.id,column.particle.size,column.temperature,column.flowrate,column.t0
0,1,Waters ACQUITY UPLC HSS T3,L1,150.0,2.1,1.8,40.0,0.28,1.18125
1,1,Waters ACQUITY UPLC HSS T3,L1,150.0,2.1,1.8,40.0,0.28,1.18125
2,1,Waters ACQUITY UPLC HSS T3,L1,150.0,2.1,1.8,40.0,0.28,1.18125
3,1,Waters ACQUITY UPLC HSS T3,L1,150.0,2.1,1.8,40.0,0.28,1.18125
4,1,Waters ACQUITY UPLC HSS T3,L1,150.0,2.1,1.8,40.0,0.28,1.18125

In [ ]:
df_column=df_column[df_column["id"]!=20].copy()

In [ ]:
df_column.shape

(212919, 9)

In [ ]:
df_gradient = df_gradient.drop(columns=["run_duration"])
df_gradient.head()

,id,grad_start_time,grad_end_time,grad_duration,grad_n_valid_points,A_grad_1,A_grad_2,A_grad_3,A_grad_4,A_grad_5,A_grad_6,A_grad_7,A_grad_8,A_grad_9,A_grad_10,A_grad_11,A_grad_12,A_grad_13,A_grad_14,A_grad_15,A_grad_16,A_grad_17,A_grad_18,A_grad_19,A_grad_20,B_grad_1,B_grad_2,B_grad_3,B_grad_4,B_grad_5,B_grad_6,B_grad_7,B_grad_8,B_grad_9,B_grad_10,B_grad_11,B_grad_12,B_grad_13,B_grad_14,B_grad_15,B_grad_16,B_grad_17,B_grad_18,B_grad_19,B_grad_20,C_grad_1,C_grad_2,C_grad_3,C_grad_4,C_grad_5,C_grad_6,C_grad_7,C_grad_8,C_grad_9,C_grad_10,C_grad_11,C_grad_12,C_grad_13,C_grad_14,C_grad_15,C_grad_16,C_grad_17,C_grad_18,C_grad_19,C_grad_20,D_grad_1,D_grad_2,D_grad_3,D_grad_4,D_grad_5,D_grad_6,D_grad_7,D_grad_8,D_grad_9,D_grad_10,D_grad_11,D_grad_12,D_grad_13,D_grad_14,D_grad_15,D_grad_16,D_grad_17,D_grad_18,D_grad_19,D_grad_20,flow_grad_1,flow_grad_2,flow_grad_3,flow_grad_4,flow_grad_5,flow_grad_6,flow_grad_7,flow_grad_8,flow_grad_9,flow_grad_10,flow_grad_11,flow_grad_12,flow_grad_13,flow_grad_14,flow_grad_15,flow_grad_16,flow_grad_17,flow_grad_18,flow_grad_19,flow_grad_20,B_initial,B_final,B_mean_slope,B_auc,B_max,B_min,B_range,B_std
0,1,0.0,28.0,28.0,8,100.0,97.631579,90.263158,87.157895,84.210526,81.263158,78.315789,75.368421,72.421053,69.473684,66.526316,63.578947,60.631579,36.842105,7.368421,0.0,0.0,0.0,100.0,100.0,0.0,2.368421,9.736842,12.842105,15.789474,18.736842,21.684211,24.631579,27.578947,30.526316,33.473684,36.421053,39.368421,63.157895,92.631579,100.0,100.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.0,0.0,0.0,1050.0,100.0,0.0,100.0,41.664583
1,1,0.0,28.0,28.0,8,100.0,97.631579,90.263158,87.157895,84.210526,81.263158,78.315789,75.368421,72.421053,69.473684,66.526316,63.578947,60.631579,36.842105,7.368421,0.0,0.0,0.0,100.0,100.0,0.0,2.368421,9.736842,12.842105,15.789474,18.736842,21.684211,24.631579,27.578947,30.526316,33.473684,36.421053,39.368421,63.157895,92.631579,100.0,100.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.0,0.0,0.0,1050.0,100.0,0.0,100.0,41.664583
2,1,0.0,28.0,28.0,8,100.0,97.631579,90.263158,87.157895,84.210526,81.263158,78.315789,75.368421,72.421053,69.473684,66.526316,63.578947,60.631579,36.842105,7.368421,0.0,0.0,0.0,100.0,100.0,0.0,2.368421,9.736842,12.842105,15.789474,18.736842,21.684211,24.631579,27.578947,30.526316,33.473684,36.421053,39.368421,63.157895,92.631579,100.0,100.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.0,0.0,0.0,1050.0,100.0,0.0,100.0,41.664583
3,1,0.0,28.0,28.0,8,100.0,97.631579,90.263158,87.157895,84.210526,81.263158,78.315789,75.368421,72.421053,69.473684,66.526316,63.578947,60.631579,36.842105,7.368421,0.0,0.0,0.0,100.0,100.0,0.0,2.368421,9.736842,12.842105,15.789474,18.736842,21.684211,24.631579,27.578947,30.526316,33.473684,36.421053,39.368421,63.157895,92.631579,100.0,100.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.0,0.0,0.0,1050.0,100.0,0.0,100.0,41.664583
4,1,0.0,28.0,28.0,8,100.0,97.631579,90.263158,87.157895,84.210526,81.263158,78.315789,75.368421,72.421053,69.473684,66.526316,63.578947,60.631579,36.842105,7.368421,0.0,0.0,0.0,100.0,100.0,0.0,2.368421,9.736842,12.842105,15.789474,18.736842,21.684211,24.631579,27.578947,30.526316,33.473684,36.421053,39.368421,63.157895,92.631579,100.0,100.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.0,0.0,0.0,1050.0,100.0,0.0,100.0,41.664583

In [ ]:
df_gradient.shape

(212919, 113)

In [ ]:
df_final = pd.concat(
    [
        df_molecule.reset_index(drop=True),
        df_column.drop(columns=["id"]).reset_index(drop=True),
        df_gradient.drop(columns=["id"]).reset_index(drop=True)
    ],
    axis=1
)

In [ ]:
df_final.head()

,id,molecule_id,rt,fingerprint,column.name,column.usp.code,column.length,column.id,column.particle.size,column.temperature,column.flowrate,column.t0,grad_start_time,grad_end_time,grad_duration,grad_n_valid_points,A_grad_1,A_grad_2,A_grad_3,A_grad_4,A_grad_5,A_grad_6,A_grad_7,A_grad_8,A_grad_9,A_grad_10,A_grad_11,A_grad_12,A_grad_13,A_grad_14,A_grad_15,A_grad_16,A_grad_17,A_grad_18,A_grad_19,A_grad_20,B_grad_1,B_grad_2,B_grad_3,B_grad_4,B_grad_5,B_grad_6,B_grad_7,B_grad_8,B_grad_9,B_grad_10,B_grad_11,B_grad_12,B_grad_13,B_grad_14,B_grad_15,B_grad_16,B_grad_17,B_grad_18,B_grad_19,B_grad_20,C_grad_1,C_grad_2,C_grad_3,C_grad_4,C_grad_5,C_grad_6,C_grad_7,C_grad_8,C_grad_9,C_grad_10,C_grad_11,C_grad_12,C_grad_13,C_grad_14,C_grad_15,C_grad_16,C_grad_17,C_grad_18,C_grad_19,C_grad_20,D_grad_1,D_grad_2,D_grad_3,D_grad_4,D_grad_5,D_grad_6,D_grad_7,D_grad_8,D_grad_9,D_grad_10,D_grad_11,D_grad_12,D_grad_13,D_grad_14,D_grad_15,D_grad_16,D_grad_17,D_grad_18,D_grad_19,D_grad_20,flow_grad_1,flow_grad_2,flow_grad_3,flow_grad_4,flow_grad_5,flow_grad_6,flow_grad_7,flow_grad_8,flow_grad_9,flow_grad_10,flow_grad_11,flow_grad_12,flow_grad_13,flow_grad_14,flow_grad_15,flow_grad_16,flow_grad_17,flow_grad_18,flow_grad_19,flow_grad_20,B_initial,B_final,B_mean_slope,B_auc,B_max,B_min,B_range,B_std
0,1,0001_00001,12.070,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Waters ACQUITY UPLC HSS T3,L1,150.0,2.1,1.8,40.0,0.28,1.18125,0.0,28.0,28.0,8,100.0,97.631579,90.263158,87.157895,84.210526,81.263158,78.315789,75.368421,72.421053,69.473684,66.526316,63.578947,60.631579,36.842105,7.368421,0.0,0.0,0.0,100.0,100.0,0.0,2.368421,9.736842,12.842105,15.789474,18.736842,21.684211,24.631579,27.578947,30.526316,33.473684,36.421053,39.368421,63.157895,92.631579,100.0,100.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.0,0.0,0.0,1050.0,100.0,0.0,100.0,41.664583
1,1,0001_00002,15.990,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Waters ACQUITY UPLC HSS T3,L1,150.0,2.1,1.8,40.0,0.28,1.18125,0.0,28.0,28.0,8,100.0,97.631579,90.263158,87.157895,84.210526,81.263158,78.315789,75.368421,72.421053,69.473684,66.526316,63.578947,60.631579,36.842105,7.368421,0.0,0.0,0.0,100.0,100.0,0.0,2.368421,9.736842,12.842105,15.789474,18.736842,21.684211,24.631579,27.578947,30.526316,33.473684,36.421053,39.368421,63.157895,92.631579,100.0,100.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.0,0.0,0.0,1050.0,100.0,0.0,100.0,41.664583
2,1,0001_00003,8.675,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Waters ACQUITY UPLC HSS T3,L1,150.0,2.1,1.8,40.0,0.28,1.18125,0.0,28.0,28.0,8,100.0,97.631579,90.263158,87.157895,84.210526,81.263158,78.315789,75.368421,72.421053,69.473684,66.526316,63.578947,60.631579,36.842105,7.368421,0.0,0.0,0.0,100.0,100.0,0.0,2.368421,9.736842,12.842105,15.789474,18.736842,21.684211,24.631579,27.578947,30.526316,33.473684,36.421053,39.368421,63.157895,92.631579,100.0,100.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.0,0.0,0.0,1050.0,100.0,0.0,100.0,41.664583
3,1,0001_00004,7.750,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Waters ACQUITY UPLC HSS T3,L1,150.0,2.1,1.8,40.0,0.28,1.18125,0.0,28.0,28.0,8,100.0,97.631579,90.263158,87.157895,84.210526,81.263158,78.315789,75.368421,72.421053,69.473684,66.526316,63.578947,60.631579,36.842105,7.368421,0.0,0.0,0.0,100.0,100.0,0.0,2.368421,9.736842,12.842105,15.789474,18.736842,21.684211,24.631579,27.578947,30.526316,33.473684,36.421053,39.368421,63.157895,92.631579,100.0,100.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.0,0.0,0.0,1050.0,100.0,0.0,100.0,41.664583
4,1,0001_00005,10.600,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Waters ACQUITY UPLC HSS T3,L1,150.0,2.1,1.8,40.0,0.28,1.18125,0.0,28.0,28.0,8,100.0,97.631579,90.263158,87.157895,84.210526,81.263158,78.315789,75.368421,72.421053,69.473684,66.526316,63.578947,60.631579,36.842105,7.368421,0.0,0.0,0.0,100.0,100.0,0.0,2.368421,9.736842,12.842105,15.789474,18.736842,21.684211,24.631579,27.578947,30.526316,33.473684,36.421053,39.368421,63.157895,92.631579,100.0,100.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.0,0.0,0.0,1050.0,100.0,0.0,100.0,41.664583

In [ ]:
df_final.shape

(212919, 124)

In [ ]:
df_rt0=df_final[df_final["rt"]<=0.1].copy()
df_rt0.shape

(15, 124)

In [ ]:
df_rt0

,id,molecule_id,rt,fingerprint,column.name,column.usp.code,column.length,column.id,column.particle.size,column.temperature,column.flowrate,column.t0,grad_start_time,grad_end_time,grad_duration,grad_n_valid_points,A_grad_1,A_grad_2,A_grad_3,A_grad_4,A_grad_5,A_grad_6,A_grad_7,A_grad_8,A_grad_9,A_grad_10,A_grad_11,A_grad_12,A_grad_13,A_grad_14,A_grad_15,A_grad_16,A_grad_17,A_grad_18,A_grad_19,A_grad_20,B_grad_1,B_grad_2,B_grad_3,B_grad_4,B_grad_5,B_grad_6,B_grad_7,B_grad_8,B_grad_9,B_grad_10,B_grad_11,B_grad_12,B_grad_13,B_grad_14,B_grad_15,B_grad_16,B_grad_17,B_grad_18,B_grad_19,B_grad_20,C_grad_1,C_grad_2,C_grad_3,C_grad_4,C_grad_5,C_grad_6,C_grad_7,C_grad_8,C_grad_9,C_grad_10,C_grad_11,C_grad_12,C_grad_13,C_grad_14,C_grad_15,C_grad_16,C_grad_17,C_grad_18,C_grad_19,C_grad_20,D_grad_1,D_grad_2,D_grad_3,D_grad_4,D_grad_5,D_grad_6,D_grad_7,D_grad_8,D_grad_9,D_grad_10,D_grad_11,D_grad_12,D_grad_13,D_grad_14,D_grad_15,D_grad_16,D_grad_17,D_grad_18,D_grad_19,D_grad_20,flow_grad_1,flow_grad_2,flow_grad_3,flow_grad_4,flow_grad_5,flow_grad_6,flow_grad_7,flow_grad_8,flow_grad_9,flow_grad_10,flow_grad_11,flow_grad_12,flow_grad_13,flow_grad_14,flow_grad_15,flow_grad_16,flow_grad_17,flow_grad_18,flow_grad_19,flow_grad_20,B_initial,B_final,B_mean_slope,B_auc,B_max,B_min,B_range,B_std
1834,10,0010_00028,0.000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Merck Supelco Ascentis Express C18,L1,150.0,2.1,2.7,55.00,0.26,1.272115,0.0,30.00,30.00,12,68.0,67.589474,59.378947,49.842105,45.368421,42.210526,38.070175,33.929825,31.824561,29.736842,27.763158,25.789474,18.052632,6.473684,3.000000,3.000000,68.000000,68.0,68.0,68.0,32.0,32.410526,40.621053,50.157895,54.631579,57.789474,61.929825,66.070175,68.175439,70.263158,72.236842,74.210526,81.947368,93.526316,97.000000,97.000000,32.000000,32.0,32.0,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.26,0.26,0.26,0.26,0.26,0.26,0.26,0.26,0.26,0.26,0.26,0.26,0.26,0.26,0.26,0.26,0.26,0.26,0.26,0.26,32.0,32.0,0.000000,1847.0000,97.0,32.0,65.0,23.170863
24816,186,0186_00363,0.005,"[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Agilent ZORBAX Extend-C18,L1,50.0,2.1,1.8,38.47,0.10,1.102500,0.0,23.00,23.00,5,95.0,95.000000,95.000000,80.789474,53.552632,47.543860,44.719298,41.894737,39.070175,36.245614,33.421053,30.596491,27.771930,24.947368,22.122807,19.298246,16.473684,15.0,15.0,15.0,5.0,5.000000,5.000000,19.210526,46.447368,52.456140,55.280702,58.105263,60.929825,63.754386,66.578947,69.403509,72.228070,75.052632,77.877193,80.701754,83.526316,85.0,85.0,85.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,5.0,85.0,3.478261,1337.5000,85.0,5.0,80.0,35.832946
24821,186,0186_00368,0.005,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Agilent ZORBAX Extend-C18,L1,50.0,2.1,1.8,38.47,0.10,1.102500,0.0,23.00,23.00,5,95.0,95.000000,95.000000,80.789474,53.552632,47.543860,44.719298,41.894737,39.070175,36.245614,33.421053,30.596491,27.771930,24.947368,22.122807,19.298246,16.473684,15.0,15.0,15.0,5.0,5.000000,5.000000,19.210526,46.447368,52.456140,55.280702,58.105263,60.929825,63.754386,66.578947,69.403509,72.228070,75.052632,77.877193,80.701754,83.526316,85.0,85.0,85.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,5.0,85.0,3.478261,1337.5000,85.0,5.0,80.0,35.832946
24822,186,0186_00369,0.005,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Agilent ZORBAX Extend-C18,L1,50.0,2.1,1.8,38.47,0.10,1.102500,0.0,23.00,23.00,5,95.0,95.000000,95.000000,80.789474,53.552632,47.543860,44.719298,41.894737,39.070175,36.245614,33.421053,30.596491,27.771930,24.947368,22.122807,19.298246,16.473684,15.0,15.0,15.0,5.0,5.000000,5.000000,19.210526,46.447368,52.456140,55.280702,58.105263,60.929825,63.754386,66.578947,69.403509,72.228070,75.052632,77.877193,80.701754,83.526316,85.0,85.0,85.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,5.0,85.0,3.478261,1337.5000,85.0,5.0,80.0,35.832946
27748,186,0186_03295,0.005,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Agilent ZORBAX Extend-C18,L1,50.0,2.1,1.8,38.47,0.10,1.102500,0.0,23.00,23.00,5,95.0,95.000000,95.000000,80.789474,53.552632,47.543860,44.719298,41.894737,39.070175,36.245614,33.421053,30.596491,27.771930,24.947368,22.122807,19.298246,16.473684,15.0,15.0,15.0,5.0,5.000000,5.000000,19.210526,46.447368,52.456140,55.280702,58.105263,60.929825,63.754386,66.578947,69.403509,72.228070,75.052632,77.877193,80.701754,83.526316,85.0,85.0,85.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,5.0,85.0,3.478261,1337.5000,85.0,5.0,80.0,35.832946
28105,186,0186_03652,0.005,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Agilent ZORBAX Extend-C18,L1,50.0,2.1,1.8,38.47,0.10,1.102500,0.0,23.00,23.00,5,95.0,95.000000,95.000000,80.789474,53.552632,47.543860,44.719298,41.894737,39.070175,36.245614,33.421053,30.596491,27.771930,24.947368,22.122807,19.298246,16.473684,15.0,15.0,15.0,5.0,5.000000,5.000000,19.210526,46.447368,52.456140,55.280702,58.105263,60.929825,63.754386,66.578947,69.403509,72.228070,75.052632,77.877193,80.701754,83.526316,85.0,85.0,85.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,5.0,85.0,3.478261,1337.5000,85.0,5.0,80.0,35.832946
38843,186,0186_14390,0.005,"[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Agilent ZORBAX Extend-C18,L1,50.0,2.1,1.8,38.47,0.10,1.102500,0.0,23.00,23.00,5,95.0,95.000000,95.000000,80.789474,53.552632,47.543860,44.719298,41.894737,39.070175,36.245614,33.421053,30.596491,27.771930,24.947368,22.122807,19.298246,16.473684,15.0,15.0,15.0,5.0,5.000000,5.000000,19.210526,46.447368,52.456140,55.280702,58.105263,60.929825,63.754386,66.578947,69.403509,72.228070,75.052632,77.877193,80.701754,83.526316,85.0,85.0,85.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,5.0,85.0,3.478261,1337.5000,85.0,5.0,80.0,35.832946
51411,186,0186_26958,0.005,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Agilent ZORBAX Extend-C18,L1,50.0,2.1,1.8,38.47,0.10,1.102500,0.0,23.00,23.00,5,95.0,95.000000,95.000000,80.789474,53.552632,47.543860,44.719298,41.894737,39.070175,36.245614,33.421053,30.596491,27.771930,24.947368,22.122807,19.298246,16.473684,15.0,15.0,15.0,5.0,5.000000,5.000000,19.210526,46.447368,52.456140,55.280702,58.105263,60.929825,63.754386,66.578947,69.403509,72.228070,75.052632,77.877193,80.701754,83.526316,85.0,85.0,85.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,5.0,85.0,3.478261,1337.5000,85.0,5.0,80.0,35.832946
51722,186,0186_27269,0.005,"[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Agilent ZORBAX Extend-C18,L1,50.0,2.1,1.8,38.47,0.10,1.102500,0.0,23.00,23.00,5,95.0,95.000000,95.000000,80.789474,53.552632,47.543860,44.719298,41.894737,39.070175,36.245614,33.421053,30.596491,27.771930,24.947368,22.122807,19.298246,16.473684,15.0,15.0,15.0,5.0,5.000000,5.000000,19.210526,46.447368,52.456140,55.280702,58.105263,60.929825,63.754386,66.578947,69.403509,72.228070,75.052632,77.877193,80.701754,83.526316,85.0,85.0,85.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,5.0,85.0,3.478261,1337.5000,85.0,5.0,80.0,35.832946
57856,186,0186_33403,0.005,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Agilent ZORBAX Extend-C18,L1,50.0,2.1,1.8,38.47,0.10,1.102500,0.0,23.00,23.00,5,95.0,95.000000,95.000000,80.789474,53.552632,47.543860,44.719298,41.894737,39.070175,36.245614,33.421053,30.596491,27.771930,24.947368,22.122807,19.298246,16.473684,15.0,15.0,15.0,5.0,5.000000,5.000000,19.210526,46.447368,52.456140,55.280702,58.105263,60.929825,63.754386,66.578947,69.403509,72.228070,75.052632,77.877193,80.701754,83.526316,85.0,85.0,85.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,5.0,85.0,3.478261,1337.5000,85.0,5.0,80.0,35.832946
104581,186,0186_03652,0.005,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Agilent ZORBAX Extend-C18,L1,50.0,2.1,1.8,38.47,0.10,1.102500,0.0,23.00,23.00,5,95.0,95.000000,95.000000,80.789474,53.552632,47.543860,44.719298,41.894737,39.070175,36.245614,33.421053,30.596491,27.771930,24.947368,22.122807,19.298246,16.473684,15.0,15.0,15.0,5.0,5.000000,5.000000,19.210526,46.447368,52.456140,55.280702,58.105263,60.929825,63.754386,66.578947,69.403509,72.228070,75.052632,77.877193,80.701754,83.526316,85.0,85.0,85.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,5.0,85.0,3.478261,1337.5000,85.0,5.0,80.0,35.832946
106863,186,0186_14390,0.005,"[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Agilent ZORBAX Extend-C18,L1,50.0,2.1,1.8,38.47,0.10,1.102500,0.0,23.00,23.00,5,95.0,95.000000,95.000000,80.789474,53.552632,47.543860,44.719298,41.894737,39.070175,36.245614,33.421053,30.596491,27.771930,24.947368,22.122807,19.298246,16.473684,15.0,15.0,15.0,5.0,5.000000,5.000000,19.210526,46.447368,52.456140,55.280702,58.105263,60.929825,63.754386,66.578947,69.403509,72.228070,75.052632,77.877193,80.701754,83.526316,85.0,85.0,85.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,5.0,85.0,3.478261,1337.5000,85.0,5.0,80.0,35.832946
107017,186,0186_26958,0.005,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Agilent ZORBAX Extend-C18,L1,50.0,2.1,1.8,38.47,0.10,1.102500,0.0,23.00,23.00,5,95.0,95.000000,95.000000,80.789474,53.552632,47.543860,44.719298,41.894737,39.070175,36.245614,33.421053,30.596491,27.771930,24.947368,22.122807,19.298246,16.473684,15.0,15.0,15.0,5.0,5.000000,5.000000,19.210526,46.447368,52.456140,55.280702,58.105263,60.929825,63.754386,66.578947,69.403509,72.228070,75.052632,77.877193,80.701754,83.526316,85.0,85.0,85.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,5.0,85.0,3.478261,1337.5000,85.0,5.0,80.0,35.832946
107032,186,0186_27269,0.005,"[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Agilent ZORBAX Extend-C18,L1,50.0,2.1,1.8,38.47,0.10,1.102500,0.0,23.00,23.00,5,95.0,95.000000,95.000000,80.789474,53.552632,47.543860,44.719298,41.894737,39.070175,36.245614,33.421053,30.596491,27.771930,24.947368,22.122807,19.298246,16.473684,15.0,15.0,15.0,5.0,5.000000,5.000000,19.210526,46.447368,52.456140,55.280702,58.105263,60.929825,63.754386,66.578947,69.403509,72.228070,75.052632,77.877193,80.701754,83.526316,85.0,85.0,85.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,0.10,5.0,85.0,3.478261,1337.5000,85.0,5.0,80.0,35.832946
161351,353,0353_00884,0.006,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Waters ACQUITY UPLC HSS C18,L1,100.0,2.1,1.8,40.00,0.40,0.551250,0.0,10.01,10.01,4,95.0,95.000000,95.000000,86.773207,77.361755,67.950303,58.538852,49.127400,39.715949,30.304497,20.893045,11.481594,2.070142,0.500000,0.500000,0.500000,0.500000,0.5,0.5,0.5,5.0,5.000000,5.000000,13.226793,22.638245,32.049697,41.461148,50.872600,60.284051,69.695503,79.106955,88.518406,97.929858,99.500000,99.500000,99.500000,99.500000,99.5,99.5,99.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.40,0.40,0.40,0.40,0.40,0.40,0.40,0.40,0.40,0.40,0.40,0.40,0.40,0.40,0.40,0.40,0.40,0.40,0.40,0.40,5.0,99.5,9.440559,640.2025,99.5,5.0,94.5,47.250000

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split


def split_rt_dataset_stratified_by_id(
    df,
    target_col="rt",
    id_col="id",
    test_size=0.15,
    val_size=0.15,
    random_state=42
):
    """
    Divide el dataset original en train, validation y test
    manteniendo la proporción de cada id en los tres subconjuntos.

    Ejemplo:
    si un id tiene 100 instancias, intentará dejar:
    - 70 en train
    - 15 en validation
    - 15 en test

    Importante:
    - elimina filas sin target válido
    - hace split estratificado por id
    """

    df = df.copy()

    # Convertir target a numérico
    df[target_col] = pd.to_numeric(df[target_col], errors="coerce")

    # Eliminar filas sin target válido
    df = df.dropna(subset=[target_col]).copy()

    # Comprobar que existe la columna id
    if id_col not in df.columns:
        raise ValueError(f"La columna '{id_col}' no existe en el dataframe.")

    # Primer split: train / temp
    train_df, temp_df = train_test_split(
        df,
        test_size=(test_size + val_size),
        random_state=random_state,
        stratify=df[id_col]
    )

    # Tamaño relativo del test dentro de temp
    relative_test_size = test_size / (test_size + val_size)

    # Segundo split: validation / test
    val_df, test_df = train_test_split(
        temp_df,
        test_size=relative_test_size,
        random_state=random_state,
        stratify=temp_df[id_col]
    )

    return train_df, val_df, test_df

In [ ]:


train_df, val_df, test_df = split_rt_dataset_stratified_by_id(
    df_final,
    target_col="rt",
    id_col="id",
    test_size=0.15,
    val_size=0.15,
    random_state=42
)

# Guardar subconjuntos
train_df.to_csv("train.tsv", sep="\t", index=False)
val_df.to_csv("validation.tsv", sep="\t", index=False)
test_df.to_csv("test.tsv", sep="\t", index=False)

print("Splits guardados correctamente:")
print(f"Train: {train_df.shape}")
print(f"Validation: {val_df.shape}")
print(f"Test: {test_df.shape}")

Splits guardados correctamente:
Train: (149043, 124)
Validation: (31938, 124)
Test: (31938, 124)

In [ ]:
def check_id_proportions(train_df, val_df, test_df, id_col="id"):
    train_counts = train_df[id_col].value_counts().sort_index()
    val_counts = val_df[id_col].value_counts().sort_index()
    test_counts = test_df[id_col].value_counts().sort_index()

    total_counts = train_counts.add(val_counts, fill_value=0).add(test_counts, fill_value=0)

    proportions_df = pd.DataFrame({
        "total": total_counts,
        "train": train_counts,
        "val": val_counts,
        "test": test_counts
    }).fillna(0)

    proportions_df["train_ratio"] = proportions_df["train"] / proportions_df["total"]
    proportions_df["val_ratio"] = proportions_df["val"] / proportions_df["total"]
    proportions_df["test_ratio"] = proportions_df["test"] / proportions_df["total"]

    return proportions_df

In [ ]:
check_df = check_id_proportions(train_df, val_df, test_df, id_col="id")
check_df.head(20)

    total  train  val  test  train_ratio  val_ratio  test_ratio
id
1      76     53   12    11     0.697368   0.157895    0.144737
2     441    309   66    66     0.700680   0.149660    0.149660
3     105     74   15    16     0.704762   0.142857    0.152381
4     226    158   34    34     0.699115   0.150442    0.150442
5      88     62   13    13     0.704545   0.147727    0.147727
6      32     22    5     5     0.687500   0.156250    0.156250
7     217    152   33    32     0.700461   0.152074    0.147465
8      49     34    7     8     0.693878   0.142857    0.163265
9     573    401   86    86     0.699825   0.150087    0.150087
10    112     78   17    17     0.696429   0.151786    0.151786
13     48     34    7     7     0.708333   0.145833    0.145833
14     50     35    8     7     0.700000   0.160000    0.140000
15    155    108   24    23     0.696774   0.154839    0.148387
16     48     34    7     7     0.708333   0.145833    0.145833
19    420    294   63    63     0.700000   0.150000    0.150000
21     65     46   10     9     0.707692   0.153846    0.138462
23     79     55   12    12     0.696203   0.151899    0.151899
25    121     85   18    18     0.702479   0.148760    0.148760
27    407    285   61    61     0.700246   0.149877    0.149877
28     54     38    8     8     0.703704   0.148148    0.148148

In [ ]:
from google.colab import files
files.download("train.tsv")
files.download("validation.tsv")
files.download("test.tsv")