In [ ]:
import pandas as pd

df= pd.read_csv('data_no_mol_desc.tsv', sep = '\t')
df.head(100)

/tmp/ipykernel_1013/960470629.py:3: DtypeWarning: Columns (2,14) have mixed types. Specify dtype option on import or set low_memory=False.
  df= pd.read_csv('data_no_mol_desc.tsv', sep = '\t')

,id,molecule_id,name,formula,rt,smiles.std,inchi.std,inchikey.std,classyfire.kingdom,classyfire.superclass,...,B [%]_16,C [%]_16,D [%]_16,flow rate [ml/min]_16,t [min]_17,A [%]_17,B [%]_17,C [%]_17,D [%]_17,flow rate [ml/min]_17
0,1,0001_00001,epicatechin,C15H14O6,12.070,C1C(C(OC2=CC(=CC(=C21)O)O)C3=CC(=C(C=C3)O)O)O,InChI=1S/C15H14O6/c16-8-4-11(18)9-6-13(20)15(2...,PFTAWBLQPZVEMU-UHFFFAOYSA-N,Organic compounds (CHEMONTID:0000000),Phenylpropanoids and polyketides (CHEMONTID:00...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,0001_00002,epicatechin gallate,C22H18O10,15.990,C1C(C(OC2=CC(=CC(=C21)O)O)C3=CC(=C(C=C3)O)O)OC...,InChI=1S/C22H18O10/c23-11-6-14(25)12-8-19(32-2...,LSHVYAFMTMFKBA-UHFFFAOYSA-N,Organic compounds (CHEMONTID:0000000),Phenylpropanoids and polyketides (CHEMONTID:00...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,0001_00003,gallocatechin,C15H14O7,8.675,C1C(C(OC2=CC(=CC(=C21)O)O)C3=CC(=C(C(=C3)O)O)O)O,InChI=1S/C15H14O7/c16-7-3-9(17)8-5-12(20)15(22...,XMOCLSLCDHWDHP-UHFFFAOYSA-N,Organic compounds (CHEMONTID:0000000),Phenylpropanoids and polyketides (CHEMONTID:00...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1,0001_00004,"3,5-dihydroxybenzoic acid",C7H6O4,7.750,C1=C(C=C(C=C1O)O)C(=O)O,InChI=1S/C7H6O4/c8-5-1-4(7(10)11)2-6(9)3-5/h1-...,UYEMGAFJOZZIFP-UHFFFAOYSA-N,Organic compounds (CHEMONTID:0000000),Benzenoids (CHEMONTID:0002448),...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,0001_00005,4-hydroxybenzoic acid,C7H6O3,10.600,C1=CC(=CC=C1C(=O)O)O,"InChI=1S/C7H6O3/c8-6-3-1-5(2-4-6)7(9)10/h1-4,8...",FJKROLUGYXJWQN-UHFFFAOYSA-N,Organic compounds (CHEMONTID:0000000),Benzenoids (CHEMONTID:0002448),...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2,0002_00020,isorhamnetin 3-glucoside,C22H22O12,31.530,COC1=C(C=CC(=C1)C2=C(C(=O)C3=C(C=C(C=C3O2)O)O)...,InChI=1S/C22H22O12/c1-31-12-4-8(2-3-10(12)25)2...,CQLRUIIRRZYHHS-UHFFFAOYSA-N,Organic compounds (CHEMONTID:0000000),Phenylpropanoids and polyketides (CHEMONTID:00...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
96,2,0002_00021,isorhamnetin 3-rutinoside,C28H32O16,31.700,CC1C(C(C(C(O1)OCC2C(C(C(C(O2)OC3=C(OC4=CC(=CC(...,InChI=1S/C28H32O16/c1-9-18(32)21(35)23(37)27(4...,UIDGLYUNOUKLBM-UHFFFAOYSA-N,Organic compounds (CHEMONTID:0000000),Phenylpropanoids and polyketides (CHEMONTID:00...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
97,2,0002_00022,isorhapontin,C21H24O9,26.130,COC1=C(C=CC(=C1)C=CC2=CC(=CC(=C2)OC3C(C(C(C(O3...,InChI=1S/C21H24O9/c1-28-16-8-11(4-5-15(16)24)2...,KLPUXMNQDCUPNO-UHFFFAOYSA-N,Organic compounds (CHEMONTID:0000000),Phenylpropanoids and polyketides (CHEMONTID:00...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
98,2,0002_00023,kaempferol 3-glucoside,C21H20O11,31.250,C1=CC(=CC=C1C2=C(C(=O)C3=C(C=C(C=C3O2)O)O)OC4C...,InChI=1S/C21H20O11/c22-7-13-15(26)17(28)18(29)...,JPUKWEQWGBDDQB-UHFFFAOYSA-N,Organic compounds (CHEMONTID:0000000),Phenylpropanoids and polyketides (CHEMONTID:00...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99,2,0002_00024,kaempferol 3-rutinoside,C27H30O15,31.350,CC1C(C(C(C(O1)OCC2C(C(C(C(O2)OC3=C(OC4=CC(=CC(...,InChI=1S/C27H30O15/c1-9-17(31)20(34)22(36)26(3...,RTATXGUCZHCSNG-UHFFFAOYSA-N,Organic compounds (CHEMONTID:0000000),Phenylpropanoids and polyketides (CHEMONTID:00...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
!pip install rdkit

Collecting rdkit
  Downloading rdkit-2026.3.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rdkit) (2.0.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from rdkit) (11.3.0)
Downloading rdkit-2026.3.1-cp312-cp312-manylinux_2_28_x86_64.whl (37.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.0/37.0 MB 18.4 MB/s eta 0:00:00
Installing collected packages: rdkit
Successfully installed rdkit-2026.3.1

In [ ]:

import pandas as pd
import numpy as np
from rdkit import Chem, DataStructs
from rdkit.Chem import rdFingerprintGenerator

# Cargar datos
df = pd.read_csv('data_no_mol_desc.tsv', sep='\t', low_memory=False)

# Crear generador Morgan moderno
morgan_gen = rdFingerprintGenerator.GetMorganGenerator(radius=2, fpSize=2048)

def smiles_to_morgan(smiles):
    if pd.isna(smiles):
        return None

    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None

    fp = morgan_gen.GetFingerprint(mol)
    arr = np.zeros((2048,), dtype=np.int8)
    DataStructs.ConvertToNumpyArray(fp, arr)
    return arr

# Guardarlo directamente en df
df = df.copy()
df.loc[:, "fingerprint"] = df["smiles.std"].apply(smiles_to_morgan)


# Ver algunas filas
print(df[["smiles.std", "fingerprint"]].head())

[07:28:35] WARNING: not removing hydrogen atom without neighbors
[07:28:35] WARNING: not removing hydrogen atom without neighbors
[07:28:35] WARNING: not removing hydrogen atom without neighbors
[07:28:36] WARNING: not removing hydrogen atom without neighbors
[07:28:36] WARNING: not removing hydrogen atom without neighbors
[07:28:36] WARNING: not removing hydrogen atom without neighbors
[07:28:36] WARNING: not removing hydrogen atom without neighbors
[07:28:36] WARNING: not removing hydrogen atom without neighbors
[07:28:36] WARNING: not removing hydrogen atom without neighbors
[07:28:37] WARNING: not removing hydrogen atom without neighbors
[07:28:37] WARNING: not removing hydrogen atom without neighbors
[07:28:37] WARNING: not removing hydrogen atom without neighbors
[07:28:37] WARNING: not removing hydrogen atom without neighbors
[07:28:37] WARNING: not removing hydrogen atom without neighbors
[07:28:37] WARNING: not removing hydrogen atom without neighbors
[07:28:37] WARNING: not removing hydrogen atom without neighbors
[07:28:38] WARNING: not removing hydrogen atom without neighbors
[07:28:38] WARNING: not removing hydrogen atom without neighbors
[07:28:38] WARNING: not removing hydrogen atom without neighbors
[07:28:38] WARNING: not removing hydrogen atom without neighbors
[07:28:38] WARNING: not removing hydrogen atom without neighbors
[07:28:38] WARNING: not removing hydrogen atom without neighbors
[07:28:38] WARNING: not removing hydrogen atom without neighbors
[07:28:39] WARNING: not removing hydrogen atom without neighbors
[07:28:43] WARNING: not removing hydrogen atom without neighbors
[07:28:43] WARNING: not removing hydrogen atom without neighbors
[07:28:43] WARNING: not removing hydrogen atom without neighbors
[07:28:43] WARNING: not removing hydrogen atom without neighbors
[07:28:43] WARNING: not removing hydrogen atom without neighbors
[07:28:43] WARNING: not removing hydrogen atom without neighbors
[07:28:43] WARNING: not removing hydrogen atom without neighbors
[07:28:43] WARNING: not removing hydrogen atom without neighbors
[07:28:43] WARNING: not removing hydrogen atom without neighbors
[07:28:43] WARNING: not removing hydrogen atom without neighbors
[07:28:43] WARNING: not removing hydrogen atom without neighbors
[07:28:43] WARNING: not removing hydrogen atom without neighbors
[07:28:44] WARNING: not removing hydrogen atom without neighbors
[07:28:44] WARNING: not removing hydrogen atom without neighbors
[07:28:44] WARNING: not removing hydrogen atom without neighbors
[07:28:44] WARNING: not removing hydrogen atom without neighbors
[07:28:44] WARNING: not removing hydrogen atom without neighbors
[07:28:44] WARNING: not removing hydrogen atom without neighbors
[07:28:44] WARNING: not removing hydrogen atom without neighbors
[07:28:45] WARNING: not removing hydrogen atom without neighbors
[07:28:45] WARNING: not removing hydrogen atom without neighbors
[07:28:45] WARNING: not removing hydrogen atom without neighbors
[07:28:45] WARNING: not removing hydrogen atom without neighbors
[07:28:45] WARNING: not removing hydrogen atom without neighbors
[07:28:45] WARNING: not removing hydrogen atom without neighbors
[07:28:45] WARNING: not removing hydrogen atom without neighbors
[07:28:45] WARNING: not removing hydrogen atom without neighbors
[07:28:45] WARNING: not removing hydrogen atom without neighbors
[07:28:45] WARNING: not removing hydrogen atom without neighbors
[07:28:45] WARNING: not removing hydrogen atom without neighbors
[07:28:46] WARNING: not removing hydrogen atom without neighbors
[07:28:46] WARNING: not removing hydrogen atom without neighbors
[07:28:46] WARNING: not removing hydrogen atom without neighbors
[07:28:46] WARNING: not removing hydrogen atom without neighbors
[07:28:46] WARNING: not removing hydrogen atom without neighbors
[07:28:46] WARNING: not removing hydrogen atom without neighbors
[07:28:46] WARNING: not removing hydrogen atom without neighbors
[07:28:47] WARNING: not removing hydrogen atom without neighbors
[07:28:47] WARNING: not removing hydrogen atom without neighbors
[07:28:47] WARNING: not removing hydrogen atom without neighbors
[07:28:47] WARNING: not removing hydrogen atom without neighbors
[07:28:47] WARNING: not removing hydrogen atom without neighbors
[07:28:47] WARNING: not removing hydrogen atom without neighbors
[07:28:47] WARNING: not removing hydrogen atom without neighbors
[07:28:47] WARNING: not removing hydrogen atom without neighbors
[07:28:47] WARNING: not removing hydrogen atom without neighbors
[07:28:47] WARNING: not removing hydrogen atom without neighbors
[07:28:47] WARNING: not removing hydrogen atom without neighbors
[07:28:48] WARNING: not removing hydrogen atom without neighbors
[07:28:48] WARNING: not removing hydrogen atom without neighbors
[07:28:48] WARNING: not removing hydrogen atom without neighbors
[07:28:48] WARNING: not removing hydrogen atom without neighbors
[07:28:48] WARNING: not removing hydrogen atom without neighbors
[07:28:48] WARNING: not removing hydrogen atom without neighbors

                                          smiles.std  \
0      C1C(C(OC2=CC(=CC(=C21)O)O)C3=CC(=C(C=C3)O)O)O
1  C1C(C(OC2=CC(=CC(=C21)O)O)C3=CC(=C(C=C3)O)O)OC...
2   C1C(C(OC2=CC(=CC(=C21)O)O)C3=CC(=C(C(=C3)O)O)O)O
3                            C1=C(C=C(C=C1O)O)C(=O)O
4                               C1=CC(=CC=C1C(=O)O)O

                                         fingerprint
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

In [ ]:
n_none = df["fingerprint"].isna().sum()
print("Número de fingerprints no generados:", n_none)

Número de fingerprints no generados: 0

In [ ]:
df_config_rt_finguerprints = df[["id","molecule_id", "rt", "fingerprint"]].copy()

In [ ]:
df_config_rt_finguerprints.head(100)

    id molecule_id      rt                                        fingerprint
0    1  0001_00001  12.070  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1    1  0001_00002  15.990  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
2    1  0001_00003   8.675  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
3    1  0001_00004   7.750  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
4    1  0001_00005  10.600  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
..  ..         ...     ...                                                ...
95   2  0002_00020  31.530  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
96   2  0002_00021  31.700  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
97   2  0002_00022  26.130  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
98   2  0002_00023  31.250  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
99   2  0002_00024  31.350  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

[100 rows x 4 columns]

In [ ]:
import json

df_config_rt_finguerprints_guardar = df_config_rt_finguerprints.copy()
df_config_rt_finguerprints_guardar["fingerprint"] = df_config_rt_finguerprints_guardar["fingerprint"].apply(
    lambda x: json.dumps(np.asarray(x, dtype=int).tolist())
)

df_config_rt_finguerprints_guardar.to_csv("dataset_training_fingerprint.tsv", sep="\t", index=False)

In [ ]:

from google.colab import files
files.download("dataset_training_fingerprint.tsv")